language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: flavianhautbois
  password:
    secure: dGCPoN7+Uj6GU9NJp+CFLLXc1Rq0QHbGROMZvNXBLrlcFMViq1ElLb0lQmsigUGmYBasUIBDPMzxF2eA0hNbADZicNgD+ZxqYxCEKiFScBaZ2kVzBGkIehzBJ2ui6WwrVUIQd/r8W3eT3hbexVpRNUeqK5+FgZ2/t+f6O0t0tXm/Ematz3rCw6ceBR0Siip5i9Vz7OXN/K8cLYFjRRoOT+f4HpVzaeTUlktd9M06G1WVbLv0VF4zm1R48ei32cbd2nObUYzKwBfDCBSlXGCp8vg/ErNDJ/QGIkKj71nL2lkqJkK2gKhFF4Fl6LUvBlEusw1U1fZkiwRhtE8D2u+5/1I5f8XgAL/wh3a6gj+gn0EmuDjiewahQEdpLBWlNwYl7SAdIjvZ/Re/vi0UB9cxW1FRL92uEOBF//twHh9yQ+9a5uDREpZAWlFQUNe0+YdbEa3n4KyGC/nQMW5hlPZGJ5JwyHP0ZJc7ihPTnNcl4lT2LeYXPBhYa/l4/D4de8vgIreTCsMFqpLatvG3q3nVtSUmhmo6nqBsUYwle6SWcNEr4/k5L+8A/Xns0L1HjQ9tADuxL0JKrS0Wfdh2qD1Xu+qo3GGqv6qclgvt64oWMfuX7DPFynZlWWkCcsR2CEs99moN+xiswtMNDbkTYBfg6BjTYoTCdOx+su+Hjj086aY=
  on:
    tags: true
    repo: flavianh/spark_etl_python
    python: 3.6
